package com.flint.compiler.tree.operators.nodes;

public enum ProdRootOp {
	COMP_UNIT_PRD, ACCESS_MODIFIER_PRD, CLASS_PARENTS_PRD, ARG_EXPRS_PRD, SELF_INVOCATION_PRD, EXPR_PRD, POSTFIX_EXPR_PRD, TEMPLATE_BODY_PRD, TYPE_PRD, CLASS_PARAMS_PRD, PARAM_PRD, PARAM_CLAUSES_PRD, FUN_SIG_PRD, TYPE_PARAM_PRD, CASE_CLASSES_PRD, BLOCK_EXPR_PRD, BLOCK_PRD, CONSTR_BLOCK_PRD, PATTERN1_PRD
}
